-- Insert sample gifts (you'll need to create profiles first through the app)
INSERT INTO gifts (title, description, image_url, price_range, affiliate_url, occasion, recipient, interests, submitted_by, upvotes, total_score) VALUES
('Wireless Noise-Canceling Headphones', 'Premium headphones perfect for music lovers and remote workers. Excellent sound quality with active noise cancellation.', '/placeholder.svg?height=300&width=300', '$200-300', 'https://amazon.com/example-headphones', 'Birthday', 'Tech Enthusiast', ARRAY['Technology', 'Music'], (SELECT id FROM profiles LIMIT 1), 15, 15),
('Artisan Coffee Subscription', 'Monthly delivery of freshly roasted, single-origin coffee beans from around the world. Perfect for coffee connoisseurs.', '/placeholder.svg?height=300&width=300', '$30-50/month', 'https://example-coffee.com/subscription', 'Any Occasion', 'Coffee Lover', ARRAY['Food & Drink', 'Subscription'], (SELECT id FROM profiles LIMIT 1), 12, 12),
('Smart Plant Monitor', 'IoT device that monitors soil moisture, light, and temperature for houseplants. Sends alerts to your phone.', '/placeholder.svg?height=300&width=300', '$50-75', 'https://amazon.com/plant-monitor', 'Housewarming', 'Plant Parent', ARRAY['Technology', 'Gardening'], (SELECT id FROM profiles LIMIT 1), 8, 8),
('Personalized Star Map', 'Custom star map showing the night sky from any date and location. Beautiful wall art with personal meaning.', '/placeholder.svg?height=300&width=300', '$40-80', 'https://etsy.com/star-map', 'Anniversary', 'Romantic Partner', ARRAY['Art', 'Personalized'], (SELECT id FROM profiles LIMIT 1), 20, 20),
('Cooking Class Experience', 'Hands-on cooking class with professional chef. Learn new cuisines and techniques in a fun group setting.', '/placeholder.svg?height=300&width=300', '$100-150', 'https://example-cooking.com/classes', 'Birthday', 'Foodie', ARRAY['Food & Drink', 'Experience'], (SELECT id FROM profiles LIMIT 1), 18, 18),
('Weighted Blanket', 'Therapeutic weighted blanket for better sleep and anxiety relief. Available in multiple weights and colors.', '/placeholder.svg?height=300&width=300', '$60-120', 'https://amazon.com/weighted-blanket', 'Self Care', 'Anyone', ARRAY['Health & Wellness', 'Sleep'], (SELECT id FROM profiles LIMIT 1), 14, 14),
('Vintage Vinyl Record Player', 'Retro-style turntable with modern features. Perfect for vinyl enthusiasts and music lovers.', '/placeholder.svg?height=300&width=300', '$150-250', 'https://amazon.com/record-player', 'Christmas', 'Music Lover', ARRAY['Music', 'Vintage'], (SELECT id FROM profiles LIMIT 1), 16, 16),
('Succulent Garden Kit', 'Complete kit with 6 different succulents, decorative pots, and care instructions. Perfect for beginners.', '/placeholder.svg?height=300&width=300', '$25-40', 'https://etsy.com/succulent-kit', 'Thank You', 'Plant Beginner', ARRAY['Gardening', 'DIY'], (SELECT id FROM profiles LIMIT 1), 11, 11);
